# **Index in MYSQL**

### *Index Exampĺe*

**All data types with built-in indexes**
* Primary key
* Unique
* Foreign key

**When to use indexes**
* Buscar una columna en el WHERE
* Ordenar una columna en el ORDER BY
* Al grupar (GROUP BY)
* Al usar MIN() y MAX()
* Modificaciones con restricciones (UNIQUE, PRIMARY KEY)

**When to not use indexes**
* En columnas donde no se busque ni se ordene
* En las columnas con baja cardinalidad (p. ej. sexo)
* Cuando en las búsquedas u ordenaciones se acompañe de otra columna
indexada con mucha mayor cardinalidad. Por ejemplo:

```sql
select * from dni = '111111' and letra = 'A'
```

**Syntax Example**

```sql
create table usuario(
    id int not null,
    apellidos char(30) not null,
    nombre char(30) not null,
    primary key(id),
    index indice01(apellidos, nombre)
);

-- OR --

create index [nombre_de_indeice] on nombre_de_tabla (columna1 [,columna2...]);

describe usuario;
show keys from usuario;
```

**FULLTEXT INDEX**

```sql
create table articles(
    id int unsigned auto_increment not null primary key,
    title varchar(200),
    body text,
    fulltext(title, body)
);

describe articles;
show index from articles;
```

**Eliminate Indexes**

```sql
alter table nombre_de_tabla drop primary key;
alter table nombre_de_tabla drop index nombre_de_indice;
drop index nombre_de_indice on nombre_de_tabla;
```

### **Index Exercises**

**Exercise 1**

*Create an index for the attributes nombre and apellido1 on the empleado table. Then, Do a query searching for an employee with a last name of Paxton and the first name to start with the letter L
```sql
create index nombre_apellido on empleado (nombre, apellido1);

select * from empleado where apellido1 = 'Paxton' and nombre like 'L%';
```

**Exercise 2**
*Se pide crear una consulta que muestre el código del empleado, nombre, primer apellido, email y puesto de todos los empleados cuyo nombre inicie con la letra M o que tengan cargo de Director de oficina. Se debe usar índices de tipo Fulltext.*

```sql
create fulltext index index_nombre_puesto on empleado (nombre, puesto)

select codigo_empleado, nombre, apellido1, email, puesto
from empleado
where (nombre like 'M%' or puesto = 'Director de oficina');
```


**Exercise 3**
*Cree los índices necesarios en la tabla producto de la base de datos jardinería, y escriba una consulta que permita obtener el código, nombre y proveedor y la descripción de los productos cuya descripción inicie con la palabra Limpitatubos, para ello se requiere que primero se creen los índices necesarios para la tabla producto.*

```sql
create index descripcion_producto on producto (descripcion(11));

select codigo_producto, nombre, proveedor, descripcion
from producto
where descripcion like 'Limpitatubos%';
```